### ISSUE TITLE
Private Repositories

### ISSUE THREAD

**Issue by rrezino** [Memnarch/Delphinus#31]
Is it possible to work with private repositories ?

**Comment by Memnarch** [comment]
You mean with private Githubrepositories? I have not tested it (since i own no private repo) but i suspect that the query will show every visible Repository for the authenticated user. So if you own a private repository, which is only visible for you, it might only show up for you. But this has to be tested. I haven't done this yet.

**Comment by rrezino** [comment]
I tested and it works!

**Comment by Memnarch** [comment]
Thanks for this information, good to know!
