### ISSUE TITLE
Add "virtual dependencies" for Delphi & stuff "out of the box"

### ISSUE THREAD

**Issue by Pawe1** [Memnarch/Delphinus#45]
I think that there should be allowed some kind of "virtual" dependencies.
I mean dependencies to stuff installed "out of the box" like DUnit / DUnitX / Indy / ....
I think that also it should be possible to add IDE version as a dependency (like Starter / Professional or 10.1 / 10.2 / etc.) because the mechanism is similar.
I have no idea about implementation - this is only thing to consider.

Why?
Because for example Starter edition lacks DUnit
Or some ADO stuff / etc

**Comment by Memnarch** [comment]
TBH starter edition support was more or less spontaneous. I did it because it worked(limited, but worked). I won't put too much work on that to deal with certain special cases(for now). Same goes for dependencies on editions(for now). And IDE 10.1/10.2 is already possible(implicitly) since you specify CompilerVersions which goes in hand with the IDE.

BTW at work we usually evaporate the builtin Indy and use the most recent or a custom modified one. Try to control/identify that in a packagemanager oO

**Comment by Pawe1** [comment]
Ok, maybe it was not so good example with Indy :stuck_out_tongue: 
For me DUnit/DUnitX is a problem because if (Delphinus) package installer contains step with building tests it will probably fail in Delphi Starter because DUnit/DUnitX is not shipped with IDE.
But on the other side it's pointless to install DUnit in Delphi Professional+
There are other stuff like DB components...

Dependencies => I understand

So maybe Delphinus should add some environment variable for Starter or something?...

**Comment by Memnarch** [comment]
TBH tests should not build in a DelphinusPackage

**Comment by Pawe1** [comment]
I am also wondering if it would be good idea to publish DUnit mirror on GitHub for Delphinus... (I have no idea if MPL 1.1 means that it is allowed - any idea?)

But in this case I don't know if it should be possible to install DUnit in Delphi Professional because it could be already installed...
