### ISSUE TITLE
'An error occurred in the secure channel support'

### ISSUE THREAD

**Issue by M22arius** [Memnarch/Delphinus#64]
Hello, I installed Delphinus and get this error while trying to refresh/reload the packages. How can i resolve this problem?

Running Delphi XE and Windows 7

**Comment by micha137** [comment]
I think this is caused by[ GitHub disabling TLS <= 1.1](https://githubengineering.com/crypto-removal-notice/). WinHTTP, which is used by Delphinus, by default uses nothing newer than TLS 1.1,  You have to [enable newer TLS versions manually](http://www.admin-enclave.com/en/articles/windows/402-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in-winhttp.html).

**Comment by M22arius** [comment]
Thanks for the reply! Good point, I added the [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp] "DefaultSecureProtocols"=dword:00000a00, rebooted, but it did not work. It produces exactly the same error.

**Comment by micha137** [comment]
Ah, sorry.  The linked page doesn't mention that since the IDE is a 32Bit process, you have to add/change `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp`.  Notice the `Wow6432Node`.

**Comment by M22arius** [comment]
Excellent that did the trick! Don't you love windows ;)

It was indeed written in "https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in" (and as usual i did not read everything)
